[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
padding.x = 5
padding.y = 5
decorations = "full"
title = "Alacritty"
opacity = 1
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 120
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 5000
multiplier = 3

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x2E3440"
foreground = "0xD8DEE9"

[colors.normal]
black = "0x3B4252"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x88C0D0"
white = "0xE5E9F0"

[colors.bright]
black = "0x4C566A"
red = "0xBF616A"
green = "0xA3BE8C"
yellow = "0xEBCB8B"
blue = "0x81A1C1"
magenta = "0xB48EAD"
cyan = "0x8FBCBB"
white = "0xECEFF4"

[font]
size = 16

[font.normal]
family = "Iosevka Nerd Font"
style = "SemiBold"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>	"
save_to_clipboard = true

[cursor]
vi_mode_style = "Beam"
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = true

[[mouse.bindings]]
mouse = "Middle"
action = "PasteSelection"

[general]
live_config_reload = true
working_directory = "None"

[terminal]
osc52 = "CopyPaste"
shell = { program = "~/scripts/tmux/tmux.sh" }
